routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','PostController@index');
Route::resource('/post','PostController' );

Route::get('/patentes',function(){
    return view('patentes.index');
});
Route::get('/laboratorio','LaboratorioController@index')->name('laboratorio');
Route::resource('laboratorios','LaboratorioController');
Auth::routes();
Route::get('/quemsomos',function(){
    return view('quemsomos');
})->name('quemsomos');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function (){
    Route::get('/create', 'PostController@create');
    Route::get('/cadastrarprofessores',function(){
        return view('professores.cadastrarprofessores');
    });
    Route::get('/Home','HomeController@index')->name('bd');

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class post extends Model
{
    protected $fillable = [ 'titulo', 'descricao', 'post' , 'autor' ];
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use App\Models\Post;
use Illuminate\Http\Request;


class PostController extends Controller

{
    public function __construct()
    {
        $this->middleware('auth')->only(['edit', 'update', 'store']);

    }

    public function index()
    {
        $post = Post::paginate(4);
        return view('welcome')->with('bd', $post);
    }

    public function create()
    {
        return view('post.criarpost');
    }

    public function show(Post $post){
        return view('post.show')->with('post',$post);
    }

    public function store(Request $request)
    {/*
        $rules = [
            'titulo' => 'required|min:3|max:50',
            'descricao' => 'required',
            'post' => 'required'
        ];
*/
        Post::create($request->all());
        return redirect()->route('home');

    }
}

resources/views/post/criarpost.blade.php
@extends('layouts.app')
@extends('layouts.link')

@section('content')
    <div class="container-fluid">
        <form method="post" class="form" action="{{route('post.store')}}">
            {{csrf_field()}}
            <div class="row">
                <div class="col col-md-2"></div>
                <div class="col col-md-8">
                    <div style="text-align: center;">
                        <h1>Criar post</h1>
                    </div>
                    <br/>
                    <hr/>
                    <br/>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <h3>Título</h3>
                        </div>
                        <div class="col col-md-9">
                            <input class="form-control" type="text" name="titulo" placeholder="Digite o título"/>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <h3>Autor</h3>
                        </div>
                        <div class="col col-md-9">
                            <input class="form-control" type="text" name="autor" placeholder="Digite seu Nome"/>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <h3>Descrição</h3>
                        </div>
                        <div class="col col-md-9">
                            <input class="form-control" type="text" name="descricao" placeholder="Digite a descricao"/>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col col-md-3">
                            <h3>Artigo</h3>
                        </div>
                        <div class="col col-md-9">
                            <textarea class="form-control-lg" name="post" style="resize: none;" cols="67" rows="10"
                                      placeholder="O artigo"></textarea>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info btn-lg">Criar o Post</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col col-md-2"></div>
    </div>

    <script>
        var textareas = document.getElementsByTagName('textarea');
        var count = textareas.length;
        for (var i = 0; i < count; i++) {
            textareas[i].onkeydown = function (e) {
                if (e.keyCode == 9 || e.which == 9) {
                    e.preventDefault();
                    var s = this.selectionStart;
                    this.value = this.value.substring(0, this.selectionStart) + "\t" + this.value.substring(this.selectionEnd);
                    this.selectionEnd = s + 1;
                }
            }
        }
    </script>
    @endsection
    </div>

resources/views/post/index.blade.php
<div class="row">
    <div class="col col-md-1 col-xs-1">
    </div>
    <div class="col col-md-2 col-xs-2">
        <div class="card post" style="width: 14rem; margin-left:2%;">
            <img class="card-img-top" src="images/noticias.png" alt="Card image cap">
        </div>
    </div>

    @foreach( $bd as $bds)
        <div style="margin-top:2%;" class="col col-md-2 col-xs-2">
            <div class="card post" style="width: 14rem; margin-left:2%;">
                <div class="zoom">
                    <a href="/eit/public/post/{{$bds->id}}">
                        <img class="card-img-top" src="images/3.jpg" alt="Card image cap">
                    </a>
                    <h5 style="text-align:center;margin-top:4%;" class="card-title titulonoticia">{{$bds->titulo}}</h5>
                </div>
            </div>
        </div>
    @endforeach
    <div class="col col-md-1 col-xs-1"></div>

</div>
<div class="row">
    <div class="col col-md-8"></div>
    <div class="col col-md-4">
        <div class="maisinformacao">
            <a class="btn btn-lg btn-primary">
                Mais notícias
            </a>
        </div>
    </div>

</div>
<!--
<div style="text-align: center;margin-top:3%;">
    { !! $bd->render() !! }</div>
-->

resources/views/post/show.blade.php
<!DOCTYPE html>
@include('layouts.link')
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @include('Layouts.Nav')
</head>
<body>
<div class="container-fluid">
    <div class="tela">
        <main role="main" class="body">
            <h1 class="titulo">{{$post->titulo}}</h1>
            <div class="row">
                <div class="col col-md-2">
                </div>
                <div class="col col-md-8">
                    <card class="card-body">
                        {!! GrahamCampbell\Markdown\Facades\Markdown::convertToHtml($post->post) !!}
                    </card>
                </div>
                <div class="col col-md-2">
                </div>
            </div>
            <footer class="blockquote-footer"></footer>

        </main>
    </div>
</div>
</main>

@include('Layouts.Footer')
</div>
</body>
</html>