routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','PostController@index');
Route::resource('/post','PostController' );

Route::get('/patentes',function(){
    return view('patentes.index');
});
Route::get('/laboratorio','LaboratorioController@index')->name('laboratorio');
Route::resource('laboratorios','LaboratorioController');
Auth::routes();
Route::get('/quemsomos',function(){
    return view('quemsomos');
})->name('quemsomos');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function (){
    Route::get('/create', 'PostController@create');
    Route::get('/cadastrarprofessores',function(){
        return view('professores.cadastrarprofessores');
    });
    Route::get('/Home','HomeController@index')->name('bd');

});

resources/views/home.blade.php
@extends('layouts.app')
@extends('layouts.link')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="alert alert-success">
                    @if (session('status'))
                    @endif
                    Seja bem-vindo, {{ Auth::user()->name }}!
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col col-md-3"></div>
            <div class="col col-md-6">

                <h1 class="text-center titulocadastrar"><i class="fas fa-database"></i>

                    Cadastrar</h1>
                <div class="coluna">
                    <a class="btn btn-lg btn-outline-primary" href="{{route('laboratorios.create')}}">
                        Cadastrar novos laboratórios
                    </a>
                    <a class="cadastrarprofessores btn btn-lg btn-outline-primary" href="#">
                        Cadastrar novos Professores
                    </a>
                    <a class="cadastrarprofessores btn btn-lg btn-outline-primary" href="#">
                        Cadastrar novos membros
                    </a>
                </div>
                <h1 class="text-center titulocadastrar"><i class="fas fa-newspaper"></i>Post</h1>
                <div class="coluna">
                    <a class="btn btn-lg btn-outline-warning" href="{{route('post.create')}}">
                        Criar novo Post
                    </a>
                </div>
                <hr/>
                <!-- Editar -->
                <h1 class="text-center titulocadastrar"><i class="fas fa-cogs"></i>
                    Listar/Editar/Remover</h1>

                <div class="coluna">
                    <a class="cadastrarprofessores btn btn-lg btn-outline-success" data-toggle="collapse"
                       href="#listarlaboratorio" role="button"
                       aria-expanded="false" aria-controls="collapseExample">
                        Listar Laboratórios
                    </a>
                    <a class="cadastrarprofessores btn btn-lg btn-outline-success" data-toggle="collapse"
                       href="#listarprofessores" role="button"
                       aria-expanded="false" aria-controls="collapseExample">
                        Listar Professores
                    </a>
                    <a class="cadastrarprofessores btn btn-lg btn-outline-success" data-toggle="collapse"
                       href="#listarmembros"
                       role="button"
                       aria-expanded="false" aria-controls="collapseExample">
                        Listar Membros
                    </a>
                </div>
                <div class="collapse" id="listarlaboratorio">
                    <div class="card card-body">
                        <table class="table ">
                            <tr>
                                <th scope="col">
                                    Título
                                </th>
                                <th scope="col">
                                    Área de atuação
                                </th>
                                <th scope="col">
                                    Local
                                </th>
                                <th scope="col">
                                    Funções
                                </th>
                            </tr>
                            <tbody>
                            <tr>
                                @foreach($bd as $bds)
                                    <td scope="row">
                                        {{$bds->titulo}}
                                    </td>
                                    <td scope="row">
                                        {{$bds->area_atuacao}}
                                    </td>
                                    <td scope="row">
                                        {{$bds->local}}
                                    </td>
                                    <td scope="row">
                                        <a style="color:#000; margin-right:30px" class="fas fa-wrench"
                                           href="/eit/public/editarlaboratorios/{{$bds->id}}"></a>
                                        <a class="fas fa-trash-alt"></a>

                                    </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
                <div class="collapse" id="listarprofessores">
                    <div class="card card-body">
                        Professores Listados
                    </div>
                </div>
                <div class="collapse" id="listarmembros">
                    <div class="card card-body">
                        Membros Listados
                    </div>
                </div>
            </div>

            <hr/>

            <!-- Remover -->
            <div class="col col-md-3"></div>

        </div>
        @endsection
    </div>

resources/views/quemsomos.blade.php
<!DOCTYPE html>
@include('layouts.link')
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @include('Layouts.Nav')
</head>
<body>
<div class="container-fluid">
    <div class="tela">
        <main role="main" class="body">
            <div style="text-align: center;">
                <h1 class="titulo">
                    Escritório de Inovação Tecnológia
                </h1>
            </div>
            <div class="row">
                <div class="col col-md-12 ">
                    <div style="text-align: center; margin-bottom:5%; margin-top:10%;">
                        <div class="row">
                            <div class="col col-md-6">
                                <p class="descricaotitulo"> O Escritório de Inovação Tecnológica (EIT) é o
                                    Núcleo de
                                    Inovação
                                    Tecnológica
                                    da Universidade Federal de Mato Grosso, criado pela Resolução CD nº 18/2007
                                    e
                                    atualizadoA\
                                    por
                                    meio da Resolução CD nº 17/2016 em consonância com o Novo Marco Legal da
                                    Inovação
                                    conforme
                                    disposto na Lei nº 13.243/2016... ​</p>
                            </div>
                            <div class="col col-md-6">
                                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                                    <div class="carousel-inner">
                                        <div class="carousel-item active">
                                            <img class="d-block img-fluid" height="500px" width="450px"
                                                 src="images/Menu1.jpg" alt="First slide">
                                        </div>
                                        <div class="carousel-item">
                                            <img class="d-block img-fluid" height="500px" width="450px"
                                                 src="images/Menu2.jpeg" alt="Second slide">
                                        </div>
                                        <div class="carousel-item">
                                            <img class="d-block img-fluid" height="500px" width="450px"
                                                 src="images/Menu3.jpg" alt="Third slide">
                                        </div>
                                    </div>
                                    <a class="carousel-control-prev" href="#carouselExampleControls"
                                       role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                    <a class="carousel-control-next" href="#carouselExampleControls"
                                       role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </div>

                            </div>
                        </div>
                        <a class="btn btn-outline-primary saibamais" data-toggle="collapse"
                           href="#collapseExample"
                           role="button" aria-expanded="false" aria-controls="collapseExample">
                            Saiba mais...
                        </a>
                        </p>
                        <div class="collapse" id="collapseExample">
                            <p class="descricaotitulo"> Idealizado pelo Escritório de Inovação Tecnológica da
                                UFMT, a plataforma “Vitrine Tecnológica” foi constituída visando mapear e
                                apresentar à comunidade os principais produtos e serviços com valor agregado a
                                partir do Ensino, Pesquisa e Inovação do ambiente produtivo da Universidade.

                                Objetiva-se, com a plataforma, apresentar as competências desenvolvidas na
                                instituição e que são oferecidas por seus laboratórios, a fim de promover a
                                interação e a formação de parcerias entre a Universidade Federal de Mato Grosso
                                e outras instituições públicas ou privadas, engajadas na geração de
                                conhecimento, inovações e valores para a sociedade.

                                Nesse sentido, a “Vitrine Tecnológica” é uma forma de mostrar o protagonismo da
                                instituição como agente transformador da realidade local, nacional e
                                internacional.

                                A plataforma está estruturada de maneira a apresentar os Pesquisadores, as
                                Propriedades Intelectuais e os Laboratórios divididos por área do conhecimento
                                em que este se insere. ​</p>
                        </div>
                        <hr/>
                    </div>
                    <div class="col col-md-1"></div>
                </div>
        </main>
    </div>
</div>
<!--
<div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
        <div class="row">
            <div class="col col-md-4">
                <div class="pesquisa"></div>
                <h1 class="titulopesquisa">Laboratórios</h1>
                <div style="text-align:center;">
                    <i class="fas fa-flask icones"></i>
                    <br/>
                    <a href="laboratorio/index" class="pesquisarlab btn btn-lg btn-outline-success">Pesquisar
                        laboratórios</a>
                </div>
            </div>
            <div class="col col-md-2"></div>
            <div class="col col-md-6">
                <div class="pesquisadescricao"></div>
                <a> Local provido de instalações, aparelhagem e produtos
                    necessários a manipulações, exames e experiências
                    efetuados no contexto de pesquisas científicas, de
                    análises médicas, análises de materiais ou de ensino
                    científico e técnico.atividade que envolve observação, experimentação ou
                    produção num campo de estudo (p.ex., o comportamento animal) ou a
                    prática de determinada arte ou habilidade ou estudo; oficina.
                    "l. de música***</a>
            </div>
            <div class="col col-md-1"></div>
        </div>
        <hr/>
        <div class="row">
            <div class="col col-md-6">
                <div class="pesquisadescricao"></div>
                <a> Aquele que ensina uma arte, uma atividade, uma ciência, uma língua, etc.
                    ,Pessoa que ensina em escola, universidade ou noutro estabelecimento de
                    ensino.,Executante de uma orquestra de primeira ordem.,Aquele que professa
                    publicamente as verdades religiosas.,Entendido, perito.,Que ensina.,professor
                    livre: o que ensina sem estipêndio do governo.</a>
            </div>

            <div class="col col-md-2"></div>
            <div class="col col-md-4">
                <div class="pesquisa"></div>
                <h1 class="titulopesquisa">Professores</h1>
                <div style="text-align:center;">
                    <i class="fas fa-book icones"></i>
                    <br/>
                    <a href="#" class="pesquisarlab btn btn-lg btn-outline-info">Pesquisar Professores</a>
                </div>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col col-md-4">
                <div class="pesquisa"></div>
                <div style="text-align: center;">
                    <h1 class="titulopesquisa">Patentes</h1>
                </div>
                <div style="text-align:center;">
                    <i class="fas fa-folder-open icones"></i>
                    <br/>
                    <a href="#" class="pesquisarlab btn btn-lg btn-outline-danger">Pesquisar Patentes</a>
                </div>
            </div>
            <div class="col col-md-2"></div>
            <div class="col col-md-6">
                <div class="pesquisadescricao"></div>
                <a> A patente é o título conferido pelo Estado àquele
                    que inventou (produto ou processo) algo e que não
                    está contido nas proibições da lei. Saiba tudo sobre
                    patentes, como tipos, requisitos, vantagens, prazo e
                    tempo de duração de uma patente.</a>
            </div>
            <div class="col col-md-1"></div>
        </div>
        <div class="row">
            <div class="col col-md-4">
                <div class="pesquisa"></div>
                <div style="text-align: center;">
                    <h1 class="titulopesquisa">VUE</h1>
                </div>
                <div style="text-align:center;">
                    <i class="fas fa-folder-open icones"></i>
                    <br/>
                    <a href="#" class="pesquisarlab btn btn-lg btn-outline-danger">Botão</a>
                </div>
            </div>
            <div class="col col-md-2"></div>
            <div class="col col-md-6" id="minhapica">
                <div class="pesquisadescricao"></div>


                <!-- ====================== -->
<!--
                <div id="teste">
                    <label>Nome</label>
                    <input class="form-control" type="text" v-model="nome" placeholder="Digite o nome">
                    <br><br>

                    <label>Telefone</label>
                    <input class="form-control" type="text" v-model="telefone"
                           placehold="digite o telefone">
                    <br><br>

                    <input type="radio" name="radio1" id="1" value="valor1">
                    <label>Valor1</label>
                    <input type="radio" name="radio1" id="2" value="valor2">
                    <label>Valor2</label>
                    <input type="radio" name="radio1" id="3" value="valor3">
                    <label>Valor3</label>
                    <br><br>

                    <select class="custom-select" id="selecao">
                        <option selected>Choose...</option>
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>

                </div>

                <!-- ====================== -->
<div class="post">
</div>
</main>
</div>
@include('Layouts.Footer')
</div>
</body>
</html>

resources/views/redesocial.blade.php
<div class="social">
    <div class="row">
        <div class="col col-md-12 col-xs-12">
            <h1 class="tituloderedesocial">Redes Sociais</h1>
        </div>
    </div>
    <div style="background-color:#3b5998;"class="row">
        <div class="col col-md-2 col-xs-2"></div>
        <div class="col col-md-4 col-xs-2">
            <div class="fb-page"
                 data-href="https://www.facebook.com/eitufmt/"
                 data-tabs="timeline"
                 data-small-header="true"
                 data-adapt-container-width="true"
                 data-hide-cover="false"
                 data-width="400"
                 data-show-facepile="false">
            </div>

        </div>
        <div class="col col-md-4">
            <h1>Curta nossa página no facebook</h1>
        </div>
        <div class="col col-md-2 col-xs-2"></div>
    </div>
</div>

resources/views/slideprincipal.blade.php
<div style="max-height:600px; max-width:620px; width: auto; height: auto;" id="carouselExampleIndicators" class="carousel slide slideprincipal" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div  class="carousel-inner">
        <div class="carousel-item active zoom">
            <img  class="w-100" src="images/Menu1.jpg" alt="First slide">
            <div class="carousel-caption d-none d-md-block fundodescricaoslide">
                <h5>Patente 1</h5>
                <p>Descricao da patente</p>
            </div>
        </div>
        <div class="carousel-item zoom">
            <img   class="w-100" src="images/2.png" alt="Second slide">
            <div class="carousel-caption d-none d-md-block ">
                <div class="fundodescricaoslide"></div>
                <h5>Patente 2</h5>
                <p>Descricao da patente</p>
            </div>
        </div>
        <div class="carousel-item zoom">
            <img height="50%" width="50%" class="w-100" src="images/3.jpg"alt="Third slide">
            <div class="carousel-caption d-none d-md-block fundodescricaoslide">
                <h5>Patente 3</h5>
                <p>Descricao da patente</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>