routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','PostController@index');
Route::resource('/post','PostController' );

Route::get('/patentes',function(){
    return view('patentes.index');
});
Route::get('/laboratorio','LaboratorioController@index')->name('laboratorio');
Route::resource('laboratorios','LaboratorioController');
Auth::routes();
Route::get('/quemsomos',function(){
    return view('quemsomos');
})->name('quemsomos');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>['auth']], function (){
    Route::get('/create', 'PostController@create');
    Route::get('/cadastrarprofessores',function(){
        return view('professores.cadastrarprofessores');
    });
    Route::get('/Home','HomeController@index')->name('bd');

});

app/Models/Laboratorio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Laboratorio extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'titulo', 'area_atuacao', 'descricao' , 'telefone' , 'email', 'atendimento' , 'local'
    ];

    public function contatos()
    {
        return $this->hasMany('App\Models\Contato');
    }
    public function projetosLab()
    {
        return $this->hasMany('App\Models\ProjetoLab');
    }
    public function responsaveisLab(){
        return $this->hasMany('App\Models\ResponsavelLab');
    }

    public function equipe(){
        return $this->hasMany('App\Models\Equipe');

    }
}

app/Http/Controllers/LaboratorioController.php
<?php

namespace App\Http\Controllers;

use App\Models\Laboratorio;
use Illuminate\Http\Request;

class LaboratorioController extends Controller
{
    public function __construct(){
        $this->middleware('auth')->only(['edit','update','store']);

    }

    public function index()
    {
        $bd = Laboratorio::all();
        return view('laboratorio.pesquisarlab')->with('bd', $bd);
    }
    public function show(Laboratorio $laboratorio){
        return view('laboratorio.show')->with('lab',$laboratorio);
    }
    public function principal(){
        return view('laboratorio.index')->name('principal');
    }
    public function edit($id)
    {
        $laboratorio = Laboratorio::findOrFail($id);
        return view('laboratorio.edit')->with('lab', $laboratorio);
    }


    public function update(Request $request, Laboratorio $laboratorio)
    {
        $laboratorio->update($request->all());
        return $laboratorio;

    }

    public function create(){
        return view('laboratorio.create');
    }
    public function store(Request $request)
    {
        // Regras de validação.
        $rules = [
            'titulo' => 'required|min:3|max:50',
            'area_atuacao' => 'required',
            'descricao' => 'required'
        ];
        $this->validate($request, $rules);
        if (Laboratorio::create($request->all())) {
            return redirect()->route('home');
        } else {
            return redirect()->route('home');
        }
    }
}

resources/views/laboratorio/LaboratorioCadastrado.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Importar arquivos AQUI -->
    <link href="{{url('css/style.css')}}" rel="stylesheet"/>
    <link rel="stylesheet" href="{{url('css/bootstrap.css')}}"/>
    <link rel="stylesheet" href="css/dataTables.bootstrap4.css"/>

</head>

<body>

<!-- Menu, não mudar entre as novas abas -->
<div class="container-fluid tela">

    @extends('layouts.app')
    @section('content')
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Muito bem!</h4>
            <p>
                Laboratório cadastrado com sucesso
            </p>
            <hr>
            <p class="mb-0">Clique no botão abaixo para cadastrar mais um laboratório</p>
            <a href="{{route('cadastrarlab')}}"class="btn btn-info" style="margin-top:20px;">Adicionar mais</a>
        </div>
</div>
@endsection
</body>
</html>

resources/views/laboratorio/ListLaboratorio.blade.php
<!DOCTYPE html>
@include('layouts.link')
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @include('Layouts.Nav')
</head>
<body>
<div class="container-fluid">
    <div class="tela">
        <main role="main" class="body">

















        </main>
    </div>
    @include('Layouts.Footer')
</div>
</body>
</html>

resources/views/laboratorio/create.blade.php
<!DOCTYPE html>
<html xmlns:v-on="http://www.w3.org/1999/xhtml">
<head>
    @extends('layouts.link')
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<!-- Menu, não mudar entre as novas abas -->
@include('Layouts.Nav')
<div class="container-fluid tela">
    <div style="text-align: center;">
        <h1 class="titulo">Cadastrar laboratórios</h1>
        <div class="row">
            <div class="col col-md-3"></div>
            <div class="col col-md-6">
                <form method="post" class="form" action="{{route('laboratorios.store')}}">
                    {{csrf_field()}}
                    <div class="form-group">

                        <div class="row ">
                            <div class="col col-md-3 CadastroLab">
                                <label>Nome do laboratório</label>
                            </div>
                            <div class="col col-md-9 ">
                                <input type="text" class="form-control" name="titulo" placeholder="Digite o nome">
                            </div>
                        </div>
                        <!-- area de atuacao -->
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Área de atuação: </label>

                            </div>
                            <div class="col col-md-9">
                                <input required type="text" class="form-control" name="area_atuacao"
                                       placeholder="Digite a área">
                            </div>
                        </div>
                        <!-- especialidade -->
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Especialidade: </label>

                            </div>
                            <div class="col col-md-9">
                                <input required type="text" class="form-control" name="especialidade"
                                       placeholder="Digite a especialidade">
                            </div>
                        </div>
                        <!-- Descrição -->
                        <div class="row" style="margin-bottom:10%;">
                            <div class="col col-md-3">
                                <label>Descrição: </label>
                            </div>
                            <div class="col col-md-9">
                                    <textarea class="form-control" name="descricao" required rows="5" cols="71"
                                              placeholder="Digite a descrição"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Imagem</label>

                            </div>
                            <div class="col col-md-5">
                                <input type="file" class="form-control"
                                       placeholder="Digite a área">
                            </div>
                        </div>

                        <!-- Contatos -->
                        <h2 class="titulocontato">Contato</h2>

                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Telefone: </label>
                            </div>
                            <div class="col col-md-9">
                                <input class="form-control" name="telefone" required
                                       placeholder="Digite o telefone">
                            </div>
                        </div>
                        <!-- E-mail -->
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>E-mail: </label>
                            </div>
                            <div class="col col-md-9">
                                <input class="form-control" type="email" name="email" required
                                       placeholder="Digite o E-mail">
                            </div>
                        </div>
                        <!-- Atendimento -->
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Horário de atendimento: </label>
                            </div>
                            <div class="col col-md-9">
                                <input class="form-control" type="text" name="atendimento" required
                                       placeholder="Digite o horário">
                            </div>
                        </div>
                        <!-- local -->
                        <div class="row">
                            <div class="col col-md-3 CadastroLab">
                                <label>Local: </label>
                            </div>
                            <div class="col col-md-9">
                                <input class="form-control" type="text" name="local" required
                                       placeholder="Digite o Local">
                            </div>
                        </div>
                        <!--  -->

                    </div>
                    <!-- Equipe -->
                    <div class="card" id="equipe">
                        <h1 class="titulocontato card-header">Equipe</h1>
                        <div id="equipe">
                            <div class="row card-body">
                                <div class="col col-md-5">
                                    <div class="row">
                                        <div class="col col-md-3 CadastroLab">
                                            <label>Nome </label>
                                        </div>
                                        <div class="col col-md-9">
                                            <input class="form-control" v-model="novapessoa" type="text" name="local"
                                                   required
                                                   placeholder="Digite o nome">
                                        </div>
                                    </div>
                                </div>
                                <div class="col col-md-5">
                                    <div class="row">
                                        <div class="col col-md-3 CadastroLab">
                                            <label>Função </label>
                                        </div>
                                        <div class="col col-md-9">
                                            <select name="funcao">
                                                <option value="Aluno"> Aluno</option>
                                                <option value="responsavel">Responsavel</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="col col-md-2">
                                    <button class="btn btn-success" v-on:click="adicionarPessoa">Adicionar</button>
                                </div>
                            </div>
                        </div>
                        <div class="card">
                            <table>
                                <thead>
                                <tr>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Funçao</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <th></th>
                                    <th></th>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="posicaobotao row">
                        <div class="col col-md-6">
                            <button class="btn btn-danger btn-lg">Cancelar</button>
                        </div>
                        <div class="col col-md-6">
                            <button type="submit" class="btn btn-info btn-lg">Cadastrar</button>
                        </div>
                    </div>
                    <!-- Projetos Ver como adicionar vários projetos.-->
                </form>
            </div>
            <div class="col col-md-3"></div>
        </div>
        @include('Layouts.Footer')
    </div>

</div>
</body>
</html>

resources/views/laboratorio/edit.blade.php
@extends('layouts.app')
@extends('layouts.link')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col col-md-2"></div>
            <div class="col col-md-8">

                <h1 class="text-center titulocadastrar"><i class="fas fa-database"></i>

                    EDITAR</h1>

                <hr/>
                <form method="post" class="form" action="{{route('laboratorios.update',$lab->id)}}">
                    {{csrf_field()}}
                    <input type="hidden" name="_method" value="patch" />
                    <div class="form-group">
                        <label>Nome do laboratório</label>
                    </div>
                    <div class="form-gruop">
                        <input type="text" class="form-group" value="{{$lab->id}}">
                    </div>
                    <input type="text" value="{{$lab->titulo}}" class="form-control" name="titulo">
                    <div class="col col-md-3 CadastroLab">
                        <label>Área de atuação: </label>

                    </div>
                    <input required type="text" class="form-control" name="area_atuacao"
                           value="{{$lab->area_atuacao}}">
                    <!-- Descrição -->
                    <label>Descrição: </label>
                    <textarea class="form-control" name="descricao" required rows="5"
                              cols="71">{{$lab->descricao}}</textarea>
                    <label>Imagem</label>

                    <input type="file" class="form-control"
                           placeholder="Digite a área">

                    <!-- Contatos -->
                    <h2 class="titulocontato">Contato</h2>

                    <label>Telefone: </label>
                    <input class="form-control" name="telefone" required
                           value="{{$lab->telefone}}">
                    <!-- E-mail -->
                    <label>E-mail: </label>
                    <input class="form-control" type="email" name="email" required
                           value="{{$lab->email}}">
                    <!-- Atendimento -->
                    <label>Horário de atendimento: </label>
                    <input class="form-control" type="text" name="atendimento" required
                           value="{{$lab->atendimento}}">
                    <!-- local -->
                    <label>Local: </label>
                    <input class="form-control" type="text" name="local" required
                           value="{{$lab->local}}">
                    <!--  -->

                    <div class="posicaobotao">
                        <div class="row">
                            <div class="col col-md-6" align="center">
                                <button class="btn btn-danger btn-lg">Cancelar</button>
                            </div>
                            <div class="col col-md-6" align="center">
                                <button type="submit" class="btn btn-info ml-auto btn-lg">Salvar</button>
                            </div>
                        </div>
                    </div>
                    <!-- Projetos Ver como adicionar vários projetos.-->
                </form>


                <!-- Remover -->
            </div>
            <div class="col col-md-2"></div>
        </div>
    </div>
@endsection

resources/views/laboratorio/index.blade.php
<!DOCTYPE html>
@include('layouts.link')
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @include('Layouts.Nav')
</head>
<body>

<!-- Menu, não mudar entre as novas abas -->


<!-- Conteudo do menu    inner cover   inicial-->

<div class="container-fluid">
    <div class="tela">
        <main role="main" class="body">

        </main>
    </div>
    @include('Layouts.Footer')
</div>
</body>
</html>

resources/views/laboratorio/pesquisarlab.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    @include('layouts.link')
    <title>Escritório de inovação e tecnologia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>
@include('Layouts.Nav')
<!-- Menu, não mudar entre as novas abas -->


<!-- Conteudo do menu    inner cover   inicial-->
<div class="container-fluid">
    <div class="tela">
        <main role="main" class="body">
            <table id="idpesquisalab" class="table table-striped tabeladatatable">
                <thead class="thead-dark">
                <tr>
                    <div style="text-align:center;">
                        <th style="text-align:center;">Título</th>
                        <th>Área de atuação</th>
                        <th>Descrição</th>
                        <th>Local</th>
                        <th>#</th>
                    </div>
                </tr>
                </thead>
                <tbody>
                @foreach($bd as $bds)
                    <tr>
                        <td scope="row">
                            {{$bds->titulo}}
                        </td>
                        <td scope="row">
                            {{$bds->area_atuacao}}
                        </td>
                        <td scope="row">
                            {{$bds->descricao}}
                        </td>
                        <td scope="row">
                            {{$bds->local}}

                        </td>
                        <td>
                            <a class="btn btn-info" href="/eit/public/laboratorios/{{$bds->id}}">Acessar</a>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </main>
    </div>
    @include('Layouts.Footer')
</div>
</body>
</html>

resources/views/laboratorio/show.blade.php
<!DOCTYPE html>
@include('layouts.link')
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Escritório de inovação e tecnologia</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<!-- Menu, não mudar entre as novas abas -->

<div class="container-fluid">

@include('Layouts.Nav')

<!-- TÍTULO -->
    @guest
    @else
        <i class="far fa-edit"></i>
        <a href="/eit/public/laboratorios/{{$lab->id}}/edit">Editar</a>
    @endguest
    <div style="text-align: center;">
        <h1 class="titulolab">
            {{$lab->titulo}}
        </h1>
    </div>
    <!--  Fim  -->
    <!-- Slides -->
    <div class="row slidecomtexto">
        <div class="col col-md-7">
            <div id="carouselExampleControls" class="carousel slide slidepersonalizado" data-ride="carousel">
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <img class="d-block img-fluid" src="../images/1.jpg" height="500px" width="350px"
                             alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="../images/2.png" height="500px" width="350px"
                             alt="Second slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block img-fluid" src="../images/3.jpg" height="500px" width="350px"
                             alt="Third slide">
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="col col-md-5 descricao">
            <h2>Área de atuação: {{$lab->area_atuacao}}</h2>
            <br/>
            <p> {{$lab->descricao}} </p>
        </div>
    </div>
    <hr class="linhaabaixo"/>
    <!-- Fim do Slide e descrição -->
    <!-- Nome dos responsáveis -->


    <div class="row">
        <div class="col col-md-1"></div>
        <div class="col col-md-5 ">
            <h2 class="responsaveis" style="text-align: center;">
                <i class="fas fa-user"></i>
                Responsáveis
            </h2>
            <table class="table table-hover tabelaresponsaveistd" id="tabelaresponsavel">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Curriculo</th>
                    <th>Função</th>
                </tr>
                </thead>
                <tr>
                    <td>Pessoa1</td>
                    <td><a href="www.google.com.br" TARGET="_blank">google</a></td>
                    <td>Diretor</td>
                </tr>
                <tr>
                    <td>Pessoa2</td>
                    <td><a HREF="www.youtube.com.br" TARGET="_blank">youtube</a></td>
                    <td>Coordenador</td>
                </tr>
            </table>
        </div>
        <div class="col col-md-5">
            <h2 style="text-align:center;" class="responsaveis"><i class="fas fa-users"></i>
                Equipe
            </h2>
            <table class="table table-hover tabelaresponsaveistd" id="tabelaEquipe">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Curriculo</th>
                    <th>Função</th>
                </tr>
                </thead>
                <tr>
                    <td>Pessoa1</td>
                    <td><a href="www.google.com.br" TARGET="_blank">google</a></td>
                    <td>Diretor</td>
                </tr>
                <tr>
                    <td>Pessoa2</td>
                    <td><a HREF="www.youtube.com.br" TARGET="_blank">youtube</a></td>
                    <td>Coordenador</td>
                </tr>
            </table>
        </div>
        <div class="col col-md-1"></div>
    </div>
    <hr class="linhaabaixo"/>
    <!-- Fim do nome dos responsáveis e Equipe -->
    <div class="row">
        <div class="col col-md-2"></div>
        <div class="col col-md-8" style="margin-bottom:50px;">
            <h2 style="text-align: center; margin-top:50px;">
                <i class="fas fa-file-alt"></i>
                Projetos
            </h2>
            <table class="table table-hover tabelaresponsaveistd" id="tabelaProjetos">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>Link para informações</th>
                    <th>Responsável</th>
                </tr>
                </thead>
                <tr>
                    <td>Extração de Dados</td>
                    <td><a href="www.google.com.br" TARGET="_blank">artigo</a></td>
                    <td>Ariel dos Santos</td>
                </tr>
                <tr>
                    <td>WEB</td>
                    <td><a HREF="www.youtube.com.br" TARGET="_blank">youtube</a></td>
                    <td>Pascal Monet</td>
                </tr>
            </table>
        </div>
        <div class="col col-md-2"></div>
    </div>
    <!-- Fim dos Projetos -->
    <hr class="linhaabaixo"/>
    <!-- Contatos -->
    <div class="row">
        <div class="col col-md-1"></div>
        <div class="col col-md-10" style="text-align: center; margin-top:20px;">
            <h2 class="contato">
                <a><i class="fas fa-phone-square"></i>
                    Contatos</a>
            </h2>
            <p>Telefone : {{$lab->telefone}}</p>
            <p>Email: {{$lab->email}}</p>
            <p>Horário de atendimento: {{$lab->atendimento}}</p>
            <p>Local do laboratório: {{$lab->local}}</p>
        </div>
        <div class="col col-md-1"></div>
    </div>
</div>
<!--Fim da aba Contatos -->
@include ('Layouts.Footer')

</body>
</html>